### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by kylecordes** [gabrielgrant/broccoli-less-single#17]
I'm having difficulty getting this working. I am 99% confident it is my fault, and incomplete understanding of one of the various tools involved.

So this is a request for something that would solve my problem and perhaps many others':

Include a complete working example in the repo or in the README. For optimal ease, have this example use Bootstrap in Less form, as that is probably the most common reason someone would come looking for this plug-in.

**Comment by jasonmit** [comment]
Here is mini example I just threw together, which includes bootstrap: https://github.com/jasonmit/broccoli-less-single-example

I'd be opened to reviewing a pull request if you want to make changes to the README where you feel it's lacking.  

I am just a little skeptical since it would be essentially covering how to setup a Brocfile and covering LessJS options, which are already documented in their respective repos.

**Comment by kylecordes** [comment]
That example is excellent; although I got past my own difficulties already, the next person coming along would probably find it quite helpful. I don't have anything detailed to propose for the README, other than a link to that example repo.

**Comment by jasonmit** [comment]
https://github.com/gabrielgrant/broccoli-less-single/commit/19e1f1fdd7043ad8d6be5766927522e38eb65f0e closes this
